// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjHTb1wQ-j9MH1rivRpTGmWbK4EGN-0XA',
    appId: '1:91552841385:android:267888a7c37068cecff3b8',
    messagingSenderId: '91552841385',
    projectId: 'd2home-191bc',
    storageBucket: 'd2home-191bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6I1QpavT6BRSvLAtBsjp6v16u06c1HKQ',
    appId: '1:91552841385:ios:660a490febe67bebcff3b8',
    messagingSenderId: '91552841385',
    projectId: 'd2home-191bc',
    storageBucket: 'd2home-191bc.firebasestorage.app',
    androidClientId: '91552841385-15q0gqefo55rmf5grsn3k39v56tc7prr.apps.googleusercontent.com',
    iosClientId: '91552841385-7l5fcd1hdhc2u7c79vo9al9npv1tob5u.apps.googleusercontent.com',
    iosBundleId: 'com.d2home.post',
  );
}
